# GolfVision Docker Compose Configuration

services:
  # Redis for job queue
  redis:
    image: redis:7-alpine
    container_name: golfvision-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Server
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    container_name: golfvision-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PORT=4000
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./temp:/app/temp
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Dashboard
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    container_name: golfvision-web
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000
      - VITE_WS_URL=ws://localhost:4000
    depends_on:
      - server
    restart: unless-stopped

  # Data Worker
  data-worker:
    build:
      context: .
      dockerfile: packages/workers/data-worker/Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - QUEUE_NAME=golfvision-jobs
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 2

  # Model Worker (Blender)
  model-worker:
    build:
      context: .
      dockerfile: packages/workers/model-worker/Dockerfile
    container_name: golfvision-model-worker
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - QUEUE_NAME=golfvision-jobs
      - BLENDER_GPU_ENABLED=true
    volumes:
      - ./temp:/app/temp
      - ./outputs:/app/outputs
      - ./packages/workers/model-worker/assets:/app/assets
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Post Worker (FFmpeg)
  post-worker:
    build:
      context: .
      dockerfile: packages/workers/post-worker/Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - QUEUE_NAME=golfvision-jobs
      - FFMPEG_THREADS=4
    volumes:
      - ./temp:/app/temp
      - ./outputs:/app/outputs
      - ./packages/workers/post-worker/assets:/app/assets
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 2

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: golfvision-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./outputs:/var/www/outputs:ro
    depends_on:
      - web
      - server
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: golfvision-network
